export const allTextureKeys = {
  button: "button",
	darkRoom: "dark_room",
	lightRoom: "light_room",
	eyelidsWoman: "eyelids_woman",
	finger: "finger",
	ice: "ice",
	pendulum: "pendulum",	
	shWoman: "sh_woman",
	starBlue: "star_blue",
	starGray: "star_gray",
	starGreen: "star_green",
	starIce: "star_ice",
	starOrange: "star_orange",
	starPink: "star_pink",
	starPurple: "star_purple",
	starRed: "star_red",
	srarWood: "star_wood",
	starYellow: "star_yellow",
	tileYellow: "tile_yellow",
	tile: "tile",
	woman: "woman",
	wood: "wood",
};

const appTextures = {
    [allTextureKeys.button]: 'img/button.png',
		[allTextureKeys.darkRoom]: 'img/dark_room.png',
		[allTextureKeys.lightRoom]: 'img/light_room.png',
		[allTextureKeys.eyelidsWoman]: 'img/eyelids_woman.png',
		[allTextureKeys.finger]: 'img/finger.png',
		[allTextureKeys.ice]: 'img/ice.png',
		[allTextureKeys.pendulum]: 'img/pendulum.png',
		[allTextureKeys.shWoman]: 'img/sh_woman.png',
		[allTextureKeys.starBlue]: 'img/star_blue.png',
		[allTextureKeys.starGray]: 'img/star_gray.png',
		[allTextureKeys.starGreen]: 'img/star_green.png',
		[allTextureKeys.starIce]: 'img/star_ice.png',
		[allTextureKeys.starOrange]: 'img/star_orange.png',
		[allTextureKeys.starPink]: 'img/star_pink.png',
		[allTextureKeys.starPurple]: 'img/star_purple.png',
		[allTextureKeys.starRed]: 'img/star_red.png',
		[allTextureKeys.srarWood]: 'img/star_wood.png',
		[allTextureKeys.starYellow]: 'img/star_yellow.png',
		[allTextureKeys.tileYellow]: 'img/tile_yellow.png',
		[allTextureKeys.tile]: 'img/tile.png',
		[allTextureKeys.woman]: 'img/woman.png',
		[allTextureKeys.wood]: 'img/wood.png'
};

export default appTextures;